- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.calibre_ebook.calibre
      - com.mattjakeman.ExtensionManager
      - com.github.tchx84.Flatseal
      - com.obsproject.Studio
      - org.kde.okular
        # - com.github.johnfactotum.Foliate
        # - com.valvesoftware.Steam
        # - org.vidoelan.VLC
        # - org.gnome.Boxes

- name: Install snaps
  community.general.snap:
    name:
      - brave
      - teams
        # - telegram-desktop

- name: Install classic snaps
  community.general.snap:
    name:
      - code
    classic: true
